apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: titra-test-2
  description: React Test
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: joseph.titra@harness.io
  lifecycle: experimental
